import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Navbar /> */}
        <div className="lg:flex flex">
          <div className="lg:w-[298px] lg:h-[1024px] lg:gap-[24px] lg:border-t-[0px] lg-border-r-[0.5px] lg:border-b-[0px] lg:border-l-[0px] hidden md:block lg:block ">
<Sidebar />
          </div>
          <div className="">
          {children}
          </div>
        </div>
        </body>
    </html>
  );
}
